_target_: src.eval.benchmark.Benchmark
dl1_name: before_virtual_anomaly_dataloader
dl2_name: after_virtual_anomaly_dataloader
dl1_columns: ["system_name"]
dl2_columns: ["system_name","f_anomaly","a_anomaly"]
hue: "system_name"
transform_name: "inverse"
anomaly_config: ["f_anomaly","a_anomaly"]
plotting_name: plot_heatmap
