# https://www.comet.ml

comet:
  _target_: pytorch_lightning.loggers.comet.CometLogger
  api_key: ${oc.env:COMET_API_KEY} # api key is loaded from environment variable
  workspace: ${oc.env:COMET_WORKSPACE} # workspace name
  project_name: ${oc.env:COMET_PROJECT_NAME} # project name
  save_dir: "${paths.output_dir}"
  rest_api_key: null
  # experiment_name: ""
  experiment_key: null # set to resume experiment
  offline: False
  prefix: ""
