
train_val:
  _target_: src.data.psm.dataset.build_dataset
  database_path: ${oc.env:PATH_DATA}
  table_name: "processed_data"
  columns: ["PSD", "system_name"]
  preload: True
  condition: 'stage =?'
  parameters: ['train']
  transform: 
    - ${transform.transform_psd}
    - ${transform.transform_label}
  _recursive_: True

test:
  _target_: src.data.psm.dataset.build_dataset
  database_path : ${oc.env:PATH_DATA}
  table_name : "processed_data"
  columns: ["PSD", "system_name"]
  transform: 
    - ${transform.transform_psd}
    - ${transform.transform_label}
  preload: True
  condition: 'stage =?'
  parameters: ['test']
  _recursive_: True

structural_anomaly:
  _target_: src.data.psm.dataset.build_dataset
  database_path : ${oc.env:PATH_DATA}
  table_name : "processed_data"
  columns: ["PSD", "system_name"]
  transform: 
    - ${transform.transform_psd} 
    - ${transform.transform_label}
  preload: True
  condition: 'stage =?'
  parameters: ['anomaly']
  _recursive_: True

before_virtual_anomaly:
  _target_: src.data.psm.dataset.build_dataset
  database_path : ${oc.env:PATH_DATA_V}
  table_name : "BEFORE_VAS"
  columns: ["PSD", "system_name"]
  transform: 
    - ${transform.transform_psd} 
    - ${transform.transform_label}
  preload: True
  _recursive_: True

after_virtual_anomaly:
  _target_: src.data.psm.dataset.build_dataset
  database_path : ${oc.env:PATH_DATA_V}
  table_name : "AFTER_VAS"
  columns: ["PSD", "system_name","frequency_a",'amplitude_a']
  transform: 
    - ${transform.transform_psd} 
    - ${transform.transform_label}
    - null
    - null
  preload: False
  _recursive_: True



