
train_val:
  _target_: src.data.psm.dataset.build_dataset
  database_path: ${oc.env:PATH_DATA}
  table_name: "processed_data"
  columns: ["PSD"]
  preload: True
  condition: 
    - 'oc'
    - 'turbine= ?'
  parameters: 
    - ['rpm_max','idle']
    - ['1','2']
  transform: 
    - ${transform.transform_psd}
    - ${transform.transform_label}
  _recursive_: True

test:
  _target_: src.data.psm.dataset.build_dataset
  database_path : ${oc.env:PATH_DATA}
  table_name : "processed_data"
  columns: ["PSD", "system_name"]
  transform: 
    - ${transform.transform_psd}
    - ${transform.transform_label}
  preload: True
  condition: 'stage =?'
  parameters: ['test']
  _recursive_: True

affected_real_anomaly:
  _target_: src.data.psm.dataset.build_dataset
  database_path : ${oc.env:PATH_DATA}
  table_name : "processed_data"
  columns: ["PSD", "system_name"]
  transform: 
    - ${transform.transform_psd} 
    - ${transform.transform_label}
  preload: True
  condition: 'stage =?'
  parameters: ['anomaly']
  _recursive_: True

reference:
  _target_: src.data.psm.dataset.build_dataset
  database_path : ${oc.env:PATH_DATA_V}
  table_name : "ORIGINAL_PSD"
  columns: ["PSD", "system_name"]
  transform: 
    - ${transform.transform_psd} 
    - ${transform.transform_label}
  preload: True
  _recursive_: True

affected_virtual_anomaly:
  _target_: src.data.psm.dataset.build_dataset
  database_path : ${oc.env:PATH_DATA_V}
  table_name : "VAS_notch"
  columns: ["PSD", "system_name"]
  transform: 
    - ${transform.transform_psd} 
    - ${transform.transform_label}
  preload: False
  _recursive_: True



