_target_: src.model.classifier.ClassifierModule

cfg:
  network :
    _target_ : "src.model.component.simple_dense_net.SimpleDenseNet"
    input_dim : ${transform.dim_psd}
    hidden_layers : [64,128,64]
    embedding_dim : 32
    output_dim : 20
    dropout : 0.5
    activation : "ReLU"
    batch_norm : True
    bias : True
    temperature : 1
    l1_regularization : 1e-4
    l2_regularization : 1e-5

  optimizer:
    _target_: torch.optim.Adam
    lr: 0.001
    weight_decay: 0.0001

  scheduler:
    _target_: torch.optim.lr_scheduler.CosineAnnealingLR
    T_max: 10
    eta_min: 1e-10
    _partial_: True
    
  loss: 
    _target_: 'torch.nn.CrossEntropyLoss'


  metric:
    _target_: "torchmetrics.Accuracy"
    task: "multiclass"
    num_classes: 20
    _partial_: True


  logging:
    on_step : False
    on_epoch : True
    sync_dist : True # sync logging across all GPUs
    prog_bar : True
  
_recursive_: False
