_target_: src.data.psm.datamodule.DataModule


train_val:
  dataset: ${dataset.train_val}
  batch_size: 64
  shuffle: True
  num_workers: 4
test:
  dataset: ${dataset.test}
  batch_size: 64
  shuffle: False
  num_workers: 4

structural_anomaly:
  dataset: ${dataset.structural_anomaly}
  batch_size: 1000
  shuffle: False
  num_workers: 1

before_virtual_anomaly:
  dataset: ${dataset.before_virtual_anomaly}
  batch_size: 40000
  shuffle: False
  num_workers: 4

after_virtual_anomaly:
  dataset: ${dataset.after_virtual_anomaly}
  batch_size: 40000
  shuffle: False
  num_workers: 4

_recursive_: True